######################################################################
# Automatically generated by qmake (3.0) Sa Jun 4 19:29:30 2016
######################################################################

TEMPLATE = vcapp
TARGET = scanrect
INCLUDEPATH += .
QT += gui
CONFIG += console

# Input
SOURCES += scanrect.cpp
